### ISSUE TITLE
tracker: sentiment analysis w/ amazon dataset

### ISSUE THREAD

**Issue by RuiFilipeCampos** [Digital-Defiance/llm-voice-chat#14]
critical

- [ ] https://github.com/Digital-Defiance/llm-voice-chat/issues/16

essential

- [ ] https://github.com/Digital-Defiance/llm-voice-chat/issues/13
- [ ] https://github.com/Digital-Defiance/llm-voice-chat/issues/11
- [ ] #15

backlog

-  [ ] https://github.com/Digital-Defiance/llm-voice-chat/issues/12

**Comment by RuiFilipeCampos** [comment]
https://github.com/Digital-Defiance/llm-voice-chat/releases/tag/asa-v0.2.0

**Comment by RuiFilipeCampos** [comment]
I'm closing this in favor of using the project view: https://github.com/orgs/Digital-Defiance/projects/11/views/1
